- ansible/roles/cfg-service/templates/dewey.properties.j2
- services/dewey/src/dewey/amq.clj
- services/dewey/src/dewey/core.clj
ENV refers to a descriptive name for the environment it's running in. This should make it possible to run dewey off the same AMQP instance in two environments (i.e., in parasitic environments) as well as making it more plausible to horizontally scale by spinning up extra instances of dewey.
As far as review, I'd like to know if this breaks something. I don't believe so, because it appears the order messages come in shouldn't matter. But others (@tedgin especially, I believe) may have clearer ideas of edge cases to consider.
> Change dewey to use a queue named indexing.ENV

- services/NotificationAgent/project.clj
It was failing to compile as a result of the compojure-api upgrade, and this set of upgrades seems to result in it actually compiling again.
I'm not completely sure which ones are required and which aren't, but all of them are worth doing; I'd just like a check that there's nothing here which will break everything. Notably I've *not* updated korma, since the change in behavior for `update` would probably require deeper changes.
> Update a bunch of notificationagent dependencies.

- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/domain/data.clj
- services/data-info/src/data_info/routes/domain/exists.clj
- services/data-info/src/data_info/routes/domain/stats.clj
- services/data-info/src/data_info/routes/domain/trash.clj
- services/data-info/src/data_info/routes/exists.clj
- services/data-info/src/data_info/routes/stats.clj
- services/data-info/src/data_info/routes/trash.clj
- services/data-info/src/data_info/services/exists.clj
- services/data-info/src/data_info/services/stat.clj
- services/data-info/src/data_info/util/schema.clj
This introduces a new DocOnly record type (and associated doc-only helper function) which allows us to get what we were actually using s/either for, i.e., having one thing for swagger documentation and something else entirely for actual schema use. It also fixes some other bits to work correctly, though there may still be pieces of documentation which do not work as expected.
I also, first, reverted my changes to String from s/Keyword, since those broke swagger docs.
Further commentary inline.
> data-info schema annoyances

- ansible/roles/de-jex/tasks/main.yaml
- ansible/roles/de-jex/templates/jex.j2
- ansible/roles/util-cfg-systemd-unit/templates/jex.service.j2
- docker/javabase/Dockerfile
- services/Infosquito/Dockerfile
- services/NotificationAgent/Dockerfile
- services/anon-files/Dockerfile
- services/apps/Dockerfile
- services/clockwork/Dockerfile
- services/data-info/Dockerfile
- services/dewey/Dockerfile
- services/info-typer/Dockerfile
- services/iplant-email/Dockerfile
- services/iplant-groups/Dockerfile
- services/kifshare/Dockerfile
- services/metadata/Dockerfile
- services/monkey/Dockerfile
- services/saved-searches/Dockerfile
- services/terrain/Dockerfile
- services/tree-urls/Dockerfile
- services/user-preferences/Dockerfile
- services/user-sessions/Dockerfile
This turned out to be a lot simpler than I expected because the JDK version of the `java` executable (as opposed to the JRE version) doesn't re-execute the command. Because of this, we can use a symbolic link to change the process name of all of our JVM services that run in Docker containers.
The JEX was a little bit different because it doesn't run in a container. This was also relatively simple however. This change involved creating a bash wrapper script that uses `exec -a` to set the process name.
> CORE-7370: modify all JVM services to have descriptive process names

- services/JEX/src/jex/incoming_xforms.clj
Jargon is unreasonably verbose. This would have prevented the disk full condition on one of the condor nodes this morning.
> Add --log-driver=none to porklock docker run commands too.

- services/apps/src/apps/clients/data_info.clj
- services/data-info/project.clj
- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/domain/common.clj
- services/data-info/src/data_info/routes/domain/data.clj
- services/data-info/src/data_info/routes/domain/stats.clj
- services/data-info/src/data_info/routes/stats.clj
- services/data-info/src/data_info/services/metadata.clj
- services/data-info/src/data_info/services/page_tabular.clj
- services/data-info/src/data_info/services/stat.clj
- services/terrain/project.clj
- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/routes/filesystem.clj
- services/terrain/src/terrain/services/buggalo.clj
- services/terrain/src/terrain/services/filesystem/manifest.clj
- services/terrain/src/terrain/services/filesystem/metadata.clj
- services/terrain/src/terrain/services/filesystem/stat.clj
- services/terrain/src/terrain/util/config.clj
I'll include a variety of comments below, interleaved. In general, this is about removing the jargon-related calls from terrain.services.filesystem.metadata, but a variety of other things were added in order to allow terrain to continue coordinating things, since chunks of that code interact with the metadata service as well.
> iRODS AVU endpoint migration

- services/terrain/src/terrain/routes/fileio.clj
- services/terrain/src/terrain/services/fileio/actions.clj
- services/terrain/src/terrain/services/filesystem/updown.clj
This makes it use the data-info logic already in services.filesystem.updown, for the display-download/special-download URL.
(This is a pretty small pull request, put up in the interest of continuing to make us use PRs better)
> CORE-6211: migrate /secured/fileio/download 

- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/domain/data.clj
- services/data-info/src/data_info/services/create.clj
- services/data-info/src/data_info/services/write.clj
- services/data-info/src/data_info/util/validators.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/services/fileio/actions.clj
- services/terrain/src/terrain/services/fileio/controllers.clj
This also lays the groundwork for migrating save and saveas, which in turn will lay the groundwork for anything else that wants to save files into iRODS (e.g. re-migrating the metadata save stuff partly out of data-info to remove its dependency on the metadata service).
> CORE-7446: migrate /secured/fileio/upload

- services/apps/src/apps/service/apps/de/permissions.clj
This is a tiny change to omit the requesting user's permissions from app permission listings.
> CORE-7456: omit the requesting user from permission listing results

- ansible/db-migrations.yaml
- ansible/playbooks/de-condor-submitter.yaml
- ansible/playbooks/de-jex.yaml
- ansible/playbooks/de-porklock.yaml
- ansible/playbooks/de-pull-images.yaml
- ansible/playbooks/de-rm-containers.yml
- ansible/playbooks/de-start-containers.yml
- ansible/playbooks/de-stop-containers.yml
- ansible/playbooks/de-ui.yaml
The intent is to create an intersection of host groups with the
`[systems]` host group. The purpose is to prevent the accidental
execution of playbooks against "non-managed" hosts in the inventory
(i.e. I don't want to accidentally install/re-configure elasticsearch
for my inventory).
CORE-7460
> Update pb hosts to prevent action on parasitic env

- services/iplant-email/conf/permanent_id_request_submitted.st
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/email.clj
The requesting user will now receive an email notification on successful submission.
The data curator email notification has been improved to include the staged path rather than the original path.
> Add email notifications for Permanent ID requesters

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/terrain.properties.j2
- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/services/write.clj
- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/services/fileio/actions.clj
- services/terrain/src/terrain/services/fileio/controllers.clj
- services/terrain/src/terrain/util/config.clj
This institutes another data-info endpoint which takes the file as a multipart request much like the upload (because that's a lot easier than trying to get compojure-api to let you use a non-json body, plus it's consistent) and overwrites it, at `PUT /data/:data-id`. It then uses it for `/secured/fileio/save` much like how `saveas` was done, turning the JSON input into a buffered input stream to send to the data-info endpoint.
> CORE-6212: migrate /secured/fileio/save (file overwrite)

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/submit/SubmitAppForPublicUseViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/toolRequest/ToolRequestStatus.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/views/cells/RequestStatusCell.java
- ui/de-lib/src/main/java/org/iplantc/de/resources/client/messages/IplantContextualHelpStrings.java
- ui/de-lib/src/main/resources/org/iplantc/de/resources/client/messages/IplantContextualHelpStrings.properties
Two tickets, one pull request.
Copied from the tickets:
CORE-3114 - At present, you can choose an App category in the Public Submission form for apps only by clicking in the check-box. To unselect a category, you to un-check the category again. It would be better if we can add support select / unselect categories just by clicking on the category itself.
CORE-5560 - The Help/Info popup lists the 7 standard Tool Request statues, and says the request will be in one of those.  With 1.8.7, arbitrary/custom status support was added.  The Help/Info popup should be updated to indicate this.
> Core 3114 & Core 5560

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/AppCategoriesView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/AppsGridView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/grid/AppsGridPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/resources/client/messages/IplantDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/categories/AppCategoriesViewDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/grid/AppsGridViewDefaultAppearance.java
- ui/de-lib/src/main/resources/org/iplantc/de/resources/client/messages/IplantDisplayStrings.properties
CORE-4791 is adding an announcement to show to the user when they've successfully copied an App.  Prior to this, there was no indication the app was copied.  The user was immediately presented with the Edit App window which made it unclear if the app was already copied or if they had to save the edit window first.
CORE-6747 is adding a message to indicate to the user when they've clicked on the HPC app category that they'll be redirected to the Agave auth page instead of a `302` error message.
> CORE-4791 & CORE-6747

- services/data-info/src/data_info/routes.clj
- services/data-info/src/data_info/routes/avus.clj
- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/domain/avus.clj
- services/data-info/src/data_info/routes/domain/data.clj
- services/data-info/src/data_info/routes/domain/rename.clj
- services/data-info/src/data_info/routes/rename.clj
A lot of my early migration work I put lots of things into the `data-info.routes.data` namespace and the `data-info.routes.domain.data` namespace, but those files were getting really big. So this splits out the AVU operations and the move/rename operations into their own namespaces, which are much more reasonably sized.
It also adds a quick note about the metadata save endpoint (which remains in the data namespace), since it should be migrated partly back up into terrain in order to decouple the data-info and metadata services.
> Refactor data-info routes.

- services/terrain/src/terrain/services/permanent_id_requests.clj
If the Permanent ID Request curated folder needs to be created, the data
curators group will get own permissions for it.
The data curators group also get own permissions for folders published
to the curated folder.
> CORE-7468 Ensure data curators get own perms on published folders.

- libs/clj-jargon/src/clj_jargon/item_ops.clj
- services/data-info/src/data_info/services/write.clj
Ticket title: You can steal ownership of files in a write-shared folder.
This was the case because both creating and overwriting files use `clj-jargon.item-ops/copy-stream`, which unconditionally called `set-owner` for the user making the request (which is to say, it allowed stealing ownership of any writeable file). This changes it to take an extra argument which can optionally turn off this behavior, and then uses this argument in `data-info.services.write` to explicitly specify when ownership should be granted (a new file) and shouldn't (modifying an existing one).
> CORE-6086: make clj-jargon.item-ops/copy-stream ownership-setting behavior configurable

- ui/de-lib/src/main/java/org/iplantc/de/fileViewers/client/presenter/MimeTypeViewerResolverFactory.java
- ui/de-lib/src/main/java/org/iplantc/de/fileViewers/client/views/AbstractStructuredTextViewer.java
As the title says, this is just allowing the BED, BOWTIE, and GTF file formats to open in Tabular View since they're tab-delimited file types.
> CORE-7474 Open BED, BOWTIE, and GTF files in Tabular View

- databases/metadata/src/main/conversions/c240_2016012701.clj
- databases/metadata/src/main/data/99_version.sql
- databases/metadata/src/main/tables/permanent_id_requests.sql
- libs/kameleon/project.clj
- services/iplant-email/conf/permanent_id_request_complete.st
- services/metadata/src/metadata/persistence/permanent_id_requests.clj
- services/metadata/src/metadata/routes/domain/permanent_id_requests.clj
- services/metadata/src/metadata/routes/permanent_id_requests.clj
- services/metadata/src/metadata/services/permanent_id_requests.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/email.clj
On successful completion, terrain now sends the new ID with the completion status, and the EZID API response is emailed to data curators with the completion notification.
Permanent ID Request details now include the original_path and a permanent_id for completed requests.
> CORE-7467 Store Permanent ID with completed Requests.

- ansible/roles/util-cfg-service/templates/terrain.properties.j2
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/config.clj
Refactored the /permanent-id-requests/:request-id/ezid endpoint to save
the new identifiers as metadata template AVUs instead of iRODS AVUs.
Also saves the current year as the publicationYear attribute, which is
also submitted with the EZID API request metadata.
> CORE-7473 Add metadata template AVUs from completed Permanent ID Request info.

- services/data-info/src/data_info/routes.clj
- services/data-info/src/data_info/routes/domain/sharing.clj
- services/data-info/src/data_info/routes/sharing.clj
- services/data-info/src/data_info/services/sharing.clj
- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/routes/filesystem.clj
- services/terrain/src/terrain/services/filesystem/sharing.clj
The first commit removes an AVU-based hack that we used to use for revoking permissions on unsharing, but don't any more. Since the code was also written to circumvent a jargon bug at the time, it also used the units field as the attribute field, so it added very unuseful AVUs, and only to user home directories, which usually the AVUs can't even be seen on.
This also migrates the start of some sharing stuff, but that will probably be refactored as I migrate the actual sharing endpoints, since I'd like to make those more file-centric. Currently the function is written to take only one permission, a list of users, and a list of files, and it assigns each user that permission on each file. With a future PR, I'll most likely change this to expect a single file (per invocation) and a list of …
> CORE-6215: migrate /secured/filesystem/anon-files

- services/data-info/src/data_info/routes/domain/trash.clj
- services/data-info/src/data_info/routes/trash.clj
- services/data-info/src/data_info/services/trash.clj
This modifies only the data-info endpoints, but since terrain serves as a pure
passthrough for these endpoints, it will also be reflected in the terrain
endpoints.
One thing I'd like someone familiar with the UI to confirm or deny for me is if this will cause problems for the UI. This result (for all affected endpoints) is parsed with `decode(HasPaths.class, json)`, but I don't know if this will ignore unrecognized keys (in this case, the `"trash-paths"` key) or error. Obviously, I'm hoping the former!
> CORE-5291: After delete, return path in trash

- ansible/inventories/example.cfg
- ansible/roles/util-cfg-service/templates/docker-cleanup/docker-gc-exclude-containers.j2
These should be the last of the elk references. It should also correct the `docker-gc.properties` build error.
> Removed more elk references

- services/jex-events/Dockerfile
This reduces the size of the image substantially, and means it's sharing more layers with our other services as well (alpine-glibc is the base image for the java base image we're using). Go's builds do rely on glibc (like java does), but we don't need the rest of ubuntu to run our stuff.
From what I can determine, this is removing four layers, all used only by this (187.7 MB, 194.5 kB, 1.895 kB, 0B) and replacing them with three (5.244MB + shared with all our other services, 0B + shared with all our other services, 6.738 MB + possibly shared but I'm not sure).
I've run this with `--version` to ensure it starts; this should be sufficient since the potential errors are mostly in it finding the libc stuff it needs.
`docker history` outputs:
```
✔ ~/Source/DE [shrink-jexevents L|✔] 
12:33 $ …
```
> Switch the base of jex-events' docker image to use jeanblanchard/alpine-glibc

- services/terrain/src/terrain/routes/permanent_id_requests.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
Updated the responses of Permanent ID Request endpoints that return a request's details to include more user info in the 'requested_by' field, such as email and first/last name.
Since the requesting user's email is now available when notifications are sent to that user, notification emails can now be enabled.
Added the new ID to the "Completion" notification update in the "comments" field, which is now included as the body of the "Completion" notification email.
> CORE-7511 Add more user info to PermID Request details.

- services/NotificationAgent/src/notification_agent/delete.clj
- services/NotificationAgent/src/notification_agent/query.clj
- ui/de-lib/src/main/java/org/iplantc/de/client/services/MessageServiceFacade.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/MessageServiceFacadeImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/DesktopView.java
- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/views/DesktopViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImpl.java
- ui/de-lib/src/test/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImplTest.java
- ui/de-lib/src/test/java/org/iplantc/de/desktop/client/views/DesktopNotifications_DesktopViewTest.java
- ui/de-lib/src/test/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImplTest.java
CORE-4345 In the Notifications window, now if you hit the "Delete All" button, it will only delete all the notifications within the category you are currently viewing (Data, Analysis, etc). If the "ALL" category is selected, then all notifications regardless of the category will get deleted.
CORE-4832 If you click either the "See All Notifications" or "See New Notifications" button in the Notification drop down menu, the Notification window will open and now the drop down will close itself instead of staying open.
> CORE-4345 & CORE-4832

- libs/clj-icat-direct/src/clj_icat_direct/queries.clj
The JOIN on the "parent" and "r_coll_main" tables would cause this query
to run for over 2 hours for our iRODS admin proxy user, which has
permissions for all folders in the data store.
> CORE-7518 Optimize count-all-items-under-folder ICAT query.

- libs/clj-icat-direct/src/clj_icat_direct/queries.clj
All fairly minor stuff, @psarando work the other day hit the big issues. But, reducing these column counts and extra CTEs should make these queries run slightly faster due to reduced memory usage and less query planning (respectively), so I figured I'd put it up.
> Minor clj-icat-direct optimizations

- services/data-info/src/data_info/routes/domain/common.clj
This makes it so that `/secured/filesystem/anon-files` will properly validate -- QA has a test which passes a misspelled key, and terrain was pulling out the nonexistent "paths" key and passing it to data-info, which was then happily doing nothing and returning rather than erroring.
> CORE-7522: require at least one path in the Paths schema.

- ansible/roles/util-cfg-service/templates/dewey.properties.j2
- ansible/roles/util-cfg-service/templates/info-typer.properties.j2
- services/dewey/dev-resources/local.properties
- services/dewey/src/dewey/amq.clj
- services/dewey/src/dewey/core.clj
- services/dewey/src/dewey/curation.clj
- services/info-typer/src/info_typer/amqp.clj
- services/info-typer/src/info_typer/config.clj
http://reference.clojurerabbitmq.info/langohr.basic.html#var-qos
basic.qos configures how many unacknowledged messages may be sent on the channel unacknowledged; by default, everything's pretty much allocated immediately, is my understanding from documentation; I'd really prefer if it was a little more divided-out. For some reason, info-typer is not getting everything at once; I'm not sure if there's some difference in the implementations such that dewey is getting them all and info-typer isn't. But in any case, this makes it explicitly configured.
I've also added a line to dewey to make it log messages in basically the same format info-typer does, i.e. `[call function] [routing-key] [message]` at the INFO level. dewey basically only logs errors without this, which makes it hard to …
> Add lb/qos calls to dewey/info-typer; standardize logging some.

- services/jobservices/src/condor-launcher/condor.go
- services/jobservices/src/condor-launcher/condor_test.go
- services/jobservices/src/configurate/configurate_test.go
- services/jobservices/src/jex-adapter/main.go
- services/jobservices/src/jex-adapter/main_test.go
- services/jobservices/src/job-status-recorder/main.go
- services/jobservices/src/job-status-recorder/main_test.go
- services/jobservices/src/job-status-to-apps-adapter/main.go
- services/jobservices/src/logcabin/logcabin.go
- services/jobservices/src/logcabin/logcabin_test.go
- services/jobservices/src/messaging/amqp.go
- services/jobservices/src/messaging/amqp_test.go
- services/jobservices/src/model/jobs_test.go
- services/jobservices/src/road-runner/containers.go
- services/jobservices/src/road-runner/containers_test.go
- services/jobservices/src/road-runner/main.go
- services/jobservices/src/road-runner/main_test.go
These are changes intended for PR #101.
`logcabin`, from the `jobservices` go service, has been updated to provide the ability to specify log-levels. All logging in the `jobservices` project has been updated to use the new `logcabin` loggers.
One other, minor, enhancements was also made. Specifically, removing the extraneous `t.Fail()` statements from the unit/integration tests.
> Jex go logging

- services/data-info/src/data_info/services/stat.clj
- services/data-info/src/data_info/util/validators.clj
Just a small bugfix. Previously it was throwing an NPE after the `(partial uuid/get-path cm)` a line below returned nil, in the case of the UUID referring to a nonexistent object.
> CORE-7552: validate UUIDs refer to extant objects in stat-gatherer endpoint.

- services/dewey/src/dewey/amq.clj
Durability means very little without this, since it would only be durable in the case of being created and the broker restarted before anything connected to it. This is because `durable` makes it stay on server restarts, but `auto-delete` makes it get deleted any time the number of consumers goes to 0 from a larger number. So, durable + auto-delete means it'd only stay around if for some reason it was created but not connected to before a server restart, which isn't exactly useful.
> Make dewey's queue declaration not auto-delete. 

- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilder.java
- ui/de-lib/src/test/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilderTest.java
This implements the UI changes necessary to take advantage of the new template metadata indexing (#91). Instead of a single `nested` query which queries the `metadata` field of the main `file` or `folder` document, this changes it so that it combines this with two other queries in a `bool` via `should`: two `has_child` queries which query the `file_metadata` and `folder_metadata` types, respectively, with their own `nested` queries against the identically-structured `metadata` field of those types. I've set these to use `score_mode` of `max`, which shouldn't really matter much because our structure only has one child document, meaning various averages, maximums, sums, etc. pretty much work the same, but I thought I may as well be explicit.
This requires the reindexing to have already been …
> CORE-7499: Add has_child queries for file and folder (template) metadata

- services/metadata/src/metadata/persistence/permanent_id_requests.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/model/PermanentIdRequestPathProvider.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/presenter/PermanentIdRequestPresenter.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/FolderPathProvider.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestProperties.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/permIdRequest/views/PermanentIdRequestViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/identifiers/PermanentIdRequest.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/permIdRequest/PermIdRequestDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/permIdRequest/PermIdRequestDisplayStrings.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/permIdRequest/PermanentIdRequestPresenterDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/permIdRequest/PermanentIdRequestViewDefaultAppearance.java
Also updated Belphegor to display "Not Found" messages for null folders in the listing grid and when the "View Metadata" action is selected.
The Perm-ID Request "View Metadata" error message also includes the request's original path.
> CORE-7550 Update terrain's Perm-ID Request endpoints to return null folders instead of errors when folder does not exist.

- services/Infosquito/project.clj
- services/Infosquito/src/infosquito/messages.clj
- services/dewey/project.clj
- services/dewey/src/dewey/amq.clj
- services/monkey/project.clj
- services/monkey/src/monkey/messenger.clj
I did the upgrade for info-typer separately since it wasn't changing major versions, but these ones are. This upgrade primarily serves to upgrade dependencies of langohr itself, including lots of bugfixes in the java rabbitmq client. I'm hoping that upgrading this will help dewey the most (as the thing handling the most messages) but it's mostly just intended as keeping on top of things.
> upgrade dewey/infosquito/monkey to langohr 3.5.1

- services/apps/src/apps/clients/notifications/job_sharing.clj
- services/apps/src/apps/persistence/jobs.clj
- services/apps/src/apps/routes/domain/analysis/listing.clj
- services/apps/src/apps/service/apps/job_listings.clj
- services/apps/src/apps/service/apps/jobs/permissions.clj
- services/apps/src/apps/service/apps/jobs/sharing.clj
This PR consists of a few different changes. The primary change was to add a Boolean flag to the analysis listing service indicating whether or not the analysis could be shared. An analysis can be shared if it does not have a parent analysis (that is, if it's not a member of an HT batch) and if all of its execution systems support analysis sharing. The rest of the changes were mostly related to validation. The only exception was the notification type used for analysis sharing notifications, which was changed from `analyses` to `analysis`.
> Analysis sharing

- services/dewey/src/dewey/config.clj
- services/dewey/src/dewey/core.clj
This makes it so the config is actually validated, and it'll make it easier to add things and use things from places outside of `dewey.core` if we want to (which I think we might for configuring an ES index, for example).
> Modernize dewey's config to use defprop etc.

- services/apps/src/apps/service/apps/jobs.clj
- services/apps/src/apps/service/apps/jobs/permissions.clj
- services/apps/src/apps/service/apps/jobs/sharing.clj
This PR includes unsharing input files when an analysis is unshared and the problems with the parameter values and relaunch info endpoints.
> CORE-7566: also unshare input files when unsharing an analysis

- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/BaseDesktopAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/Desktop.css
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/window/IplantBaseWindowAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/desktop/window/IplantWindowStyles.css
Relative paths in the CSS url field were causing 404 errors.  Switched to using full path location in the .java files which the CSS files then use.
> CORE-7573 Fix Texta Font 404 errors

- services/dewey/src/dewey/core.clj
Otherwise it throws a bunch of errors about how it can't cast a string to an integer when it tries to call `Integer/parseInt` on the value it's passed.
> Dewey's irods port as passed to irods/init needs to be a string

- libs/clj-jargon/src/clj_jargon/tickets.clj
(at least, not when we already have an IRODSAccount to be used)
Assuming this doesn't break everything, it fixes the one place we make temporary passwords. I think this could be done better, probably? There seems to be a lot of vestigial code in this area of the codebase.
I'll work on testing that this actually works tomorrow morning, anyway.
> Don't create temporary passwords for a fake user to create tickets

- libs/clj-jargon/src/clj_jargon/tickets.clj
- services/kifshare/src/kifshare/tickets.clj
Minor thing, but it seemed weird that we had one utility function for tickets in a kifshare namespace, used only once, and that was the only reason `ticket-admin-service`, which seemed intended to be private by its docstring, wasn't private.
So I moved it. ¯\\_(ツ)_/¯
> Reorganize code so clj-jargon.tickets/ticket-admin-service can be private.

- services/terrain/src/terrain/clients/data_info.clj
- ui/de-lib/src/main/java/org/iplantc/de/client/events/diskResources/DiskResourcesMovedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/services/DiskResourceMove.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/DiskResourceServiceFacade.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/DiskResourceServiceFacadeImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/util/DiskResourceUtil.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/NavigationView.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/DiskResourcePresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/callbacks/DiskResourceMoveCallback.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/presenters/navigation/NavigationPresenterImpl.java
Reverted terrain's [POST /filesystem/move endpoint](http://cyverse.github.io/DE/api/endpoints/filesystem/move.html#moving-files-andor-directories) response.
Updated the DiskResourceServiceFacadeImpl logic that updates its folder cache when folders are moved, since we can no longer lookup folders in the cache by path.
Instead, the source and destination folders are refreshed when folders have been moved to and from them.
Refreshing instead of preserving folder caches allows some DiskResourcesMovedEvent handler logic to be cleaned up in the NavigationPresenterImpl.
> CORE-7356 Fix data window updates on folder moves.

- services/terrain/src/terrain/services/admin.clj
This way, nonresponsive services are marked as non-functional in a timely fashion.
> CORE-7588: time out requests made as part of terrain's /admin/status

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/dewey.properties.j2
- ansible/roles/util-cfg-service/templates/info-typer.properties.j2
This is a pull request against the master branch to bring the AMQP broker configuration specified in ansible scripts inline with what's currently in prod.  There are corresponding changes in the `irods_amqp_cfg` branch of the `de-ansible` private repo.
> iRODS AMQP broker can now be on separate host

- ansible/inventories/example.cfg
- ansible/inventories/group_vars/all
- ansible/roles/de-rabbitmq-cfg/tasks/main.yml
- ansible/roles/util-cfg-service/templates/condor-log-monitor.properties.j2
- ansible/roles/util-cfg-service/templates/dewey.properties.j2
- ansible/roles/util-cfg-service/templates/info-typer.properties.j2
- ansible/roles/util-cfg-service/templates/infosquito.properties.j2
- ansible/roles/util-cfg-service/templates/jexevents.properties.j2
- ansible/roles/util-cfg-service/templates/jobservices.yml.j2
- ansible/roles/util-cfg-service/templates/metadata.properties.j2
- ansible/roles/util-cfg-service/templates/monkey.properties.j2
- ansible/roles/util-cfg-service/templates/templeton-incremental.yaml.j2
- ansible/roles/util-cfg-service/templates/templeton-periodic.yaml.j2
This PR expands the configuration changes that allow iRODS and the DE to use separate AMQP brokers.  A few cleanups were made as well.
> Cleaned up/generalized iRODS AMQP config changes

- services/anon-files/src/anon_files/core.clj
- services/kifshare/src/kifshare/core.clj
This way (with the appropriate environment variables and stuff in place, anyway) consul-template won't consider these services to be up until they can actually respond to an HTTP ping (i.e., when they're actually up). These just match our other services (specifically the simple ones). If we switch to using swagger for these at some point then these can become proper status endpoints like the data-info/metadata/apps ones but it doesn't matter much for consul.
> Add basic simple status check endpoints to anon-files and kifshare for consul to use.

- docker/images.txt
- docker/nginx-consul-template/Dockerfile
- docker/nginx-consul-template/nginx.conf.tmpl
- docker/nginx-consul-template/run.sh
This is the first step toward the zero-downtime deployment setup. There's still lots to do in terms of ansible changes, docker-compose file modifications, etc. (not least of all including this image in our docker-compose files) but I think this can be independently reviewed.
Most of the configuration for this comes in through environment variables. As an example:
`docker run -p 5555:5555 -e CONSUL_CONNECT=some-consul-server:8500 -e NGINX_PROXY_PORT=5555 -e NGINX_PROXY_SERVICE_NAME=anon-files -e DE_ENV=de-2 nginx-consul-template`
This invocation would run an nginx on port 5555 (in-container and outside of the container) which proxies for anon-files instances marked as being in de-2. The color (blue/green -- really just an arbitrary tag) which it should use is stored in a consul k/v; in …
> Add an nginx+consul-template dockerfile/etc. intended for use with service nginx containers.

- ansible/playbooks/de-deploy-service-nginx.yaml
This is basically: copy in everything from `de-pull-images.yaml`, remove non-HTTP services, append `_nginx`; copy in everything from `de-start-containers.yaml`, remove non-HTTP services, append `_nginx`.
We don't need to do an explicit stop/remove with this because these containers don't use config containers and thus `docker-compose up` will do the right thing for them.
> Add a playbook which deploys service nginx containers

- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/services/metadata/comments.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
This changes the data-info client's `stat-by-uuid` to use data-info rather than jargon directly. It also removes both uses of its `owns?` function (used, incidentally, the same two places) to use the `permission` value retrieved from data-info instead of calling out with jargon to check the ownership permission.
This doesn't close the ticket, which is quite large, but moves a few more things to properly use data-info instead of jargon calls in terrain.
> CORE-6259: migrate data-info/stat-by-uuid and data-info/owns? usages

- services/data-info/src/data_info/services/root.clj
I also refactored the file generally a bit to be more consistent/clear about what it's doing.
> CORE-7638: validate path readability in get-root so a nil permission can't seep through

- libs/common-swagger-api/project.clj
- libs/iplant-clojure-commons/project.clj
- services/apps/project.clj
- services/data-info/project.clj
- services/iplant-groups/project.clj
- services/metadata/project.clj
- services/terrain/project.clj
Moving to 1.0+ will require a bit of work (https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-1.0.0), but this is just bugfixes. I haven't tested everything which uses this intensively but everything compiles and the changes are pretty minimal (starting at https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#0245-1712016 and below).
> Bump compojure-api to 0.24.5.

- libs/tree-urls-client/.gitignore
- libs/tree-urls-client/project.clj
- libs/tree-urls-client/src/tree_urls_client/core.clj
- project-defs.edn
- services/terrain/project.clj
- services/terrain/src/terrain/core.clj
- services/terrain/src/terrain/services/buggalo.clj
- services/terrain/src/terrain/services/filesystem/manifest.clj
This is somewhat in anticipation of using it in data-info (for the manifest endpoint), and somewhat as a way to solicit opinions on using this sort of a tactic more generally. I really dislike how many duplicated clients for our own services we maintain, and as we move further into microservice architecture this can only get worse without a bit of deliberate action.
> Split tree urls client out from terrain and into its own library

- ansible/inventories/group_vars/all
Replaced `docker.registry.host` and `docker.registry.port` with `docker.registry.base`.
Please also review the `ansible-docker-vars-cleanup` branch in the private de-ansible repo, which is the only place where these `docker.registry.host|port` vars were used. The duplicated `docker.compose_path` was also removed from the private de-ansible repo's `group_vars/all`.
> Cleanup duplicated 'docker' group_vars.

- golang/src/messaging/amqp.go
- golang/src/templeton/main.go
Just a small thing I hadn't bothered to do correctly the first time since this wasn't implemented in the AMQP client at that point and I wanted it to get done.
> templeton: support multiple bindings on one queue so periodic mode doesn't need two queues

- libs/clj-icat-direct/src/clj_icat_direct/queries.clj
These queries count incorrectly when a user has access to a file by way of multiple groups, which the original ticket (DE-1115) was triggering in the data_commons folder. Interestingly it seems to be resolved in the production data_commons folder but I could still reproduce this in a QA environment.
These added `DISTINCT` match the ones in the better-functioning queries lower in the file in the `queries` var.
I have no doubt that clj-icat-direct could use some substantial refactoring but I wanted to get this fixed first, and then maybe look at the technical debt.
> CORE-7648: add DISTINCTs to some clj-icat-direct queries

- libs/debug-utils/.gitignore
- libs/debug-utils/project.clj
- libs/debug-utils/src/debug_utils/log_time.clj
- project-defs.edn
I've used versions of this macro a few times now and I don't want to write it again. Doing it this way means that for temporary debugging, `debug-utils` can be added to project.clj and then `log-time` can be imported and used (potentially across several projects/libraries/etc). I figured that putting this in a dedicated library was the most comfortable way to do this, rather than needing to put it into something we actually use outside of debugging, but I'm open to suggestions.
log-time runs its body, timing it, and then logs the provided label and the amount of time, indenting it by the depth of nested calls to log-time. Thus, for something like:
```clojure
(log-time "blah" 
(log-time "foo" (+ 1 1))
(log-time "bar" (dotimes [_ 77777] (+ 1 1))))
```
You'll get something like:
``` …
```
> Add a debug-utils class with a helpful log-time macro

- libs/clj-jargon/src/clj_jargon/metadata.clj
The primary goal of this is speeding up info-typer some. I was investigating why it's so slow and found that a call to `clj-jargon/attribute?` (to check if there's already an `ipc-filetype` AVU) was taking about 90ms most times it ran, which is longer than the actual file identification process. Looking deeper, what we were doing was getting all metadata for the object and then filtering it in clj-jargon down to just the one attribute, by way of a chain of functions.
This changes the chain so it requests only the AVUs it actually wants, from the start. I've also done the same for lookups by attribute + value, which were implemented in a similar fashion.
It seems to have worked, since a brief test afterwards showed the same call taking less than a quarter of the time.
> Reimplement several functions in clj-jargon to use more specific queries

- ansible/playbooks/de-deploy-service-nginx.yaml
- ansible/playbooks/de-deploy-services.yaml
* move de-ui deployment to color section
* move de-ui-nginx to service-nginx deployment
there is also a private ansible branch for this, which updates the docker-compose files (more than I already had to get the nginx working initially, which is already in the dev environment) and to the documentation (to mention the de-deploy-service-nginx.yaml playbook and when it should be run in deployments (i.e., when downtime is acceptable)
> CORE-7669: zero-downtime UI deployment

- databases/de-database-schema/src/main/conversions/c270_2016052501.clj
- databases/de-database-schema/src/main/data/99_version.sql
- databases/de-database-schema/src/main/tables/03_tools.sql
- libs/kameleon/project.clj
This pull requests adds a time_limit_seconds column to the tools table in the DE. It should be a "not null" column and defaults to 0.
A conversion named c270_2016052501.clj was added to update existing databases with the new column.
Kameleon's db version was updated to 2.7.0:20160525.01.
These was tested locally by doing the following:
* Mounting the new database.tar.gz and  facepalm uberjar files into a running discoenv/unittest-dedb:dev container and docker exec'ing the update-dev-database.sh script.
* Creating a new version of the discoenv/unittest-dedb:dev image with the changes loaded by default.
* Creating a new version of the discoenv/unittest-dedb:dev image with the changes loaded by default, and then running the the update-dev-database.sh script.
The database ships with 3 tools …
> Add a time_limit_seconds column to the tools table

- golang/src/condor-launcher/condor.go
http://research.cs.wisc.edu/htcondor/manual/v8.4/3_4User_Priorities.html#SECTION00447000000000000000
suggests that using accounting_group and accounting_group_user is the
modern way to do this, rather than using +AccountingGroup
I also moved it up in the file since we seem to roughly organize it with the submit-language stuff first and the + lines for custom attributes after.
> Use more up-to-date group accounting in submit file

- databases/de-database-schema/src/main/conversions/c270_2016052601.clj
- databases/de-database-schema/src/main/data/99_version.sql
- databases/de-database-schema/src/main/tables/03_tools.sql
- libs/kameleon/project.clj
This pull request adds a restricted column to the tools table in the DE. It should be a not null boolean column and defaults to false.
A conversion named c270_2016052601.clj was added to update existing databases with the new column.
Kameleon's db version was updated to 2.7.0:20160526.01.
These was tested locally by doing the following:
Mounting the new database.tar.gz and facepalm uberjar files into a running discoenv/unittest-dedb:dev container and docker exec'ing the update-dev-database.sh script.
Creating a new version of the discoenv/unittest-dedb:dev image with the changes loaded by default.
Creating a new version of the discoenv/unittest-dedb:dev image with the changes loaded by default, and then running the the update-dev-database.sh script.
The database ships with 3 tools …
> CORE-7676: added the restricted column to the tools table

- services/apps/src/apps/service/apps/de/jobs/common.clj
The apps service has been modified to include the time_limit_seconds and restricted fields from the tools table in the JSON sent to the jex-adapter service.
I ran the apps tests against this and there weren't any errors.
> time_limit_seconds and restricted fields are included in the job submission JSON

- ui/de-lib/src/main/java/org/iplantc/de/shared/AsyncCallbackWrapper.java
this will hopefully prevent some logouts, this is what I was getting that caused the logouts in firefox, because the requests were aborted
> Remove checking for status code 0 in AsyncCallbackWrapper 

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/apps.properties.j2
- libs/permissions-client/.gitignore
- libs/permissions-client/README.md
- libs/permissions-client/project.clj
- libs/permissions-client/src/permissions_client/core.clj
- libs/permissions-client/test/permissions_client/core_test.clj
- libs/permissions-client/test/permissions_client/integration_test.clj
This change adds a client library for the permissions service. The testing for this is fairly thorough in that it attempts to verify that client correctly constructs all URIs and returns results in the appropriate format. An exhaustive test of all permissions service features is not done here. That level of detail is left to the permissions service integration tests.
Here's an integration test running against an instance of the permissions service running on my workstation:
```
$ RUN_INTEGRATION_TESTS=1 PERMISSIONS_BASE_URI=http://localhost:60000/ lein test
lein test permissions-client.core-test
lein test permissions-client.integration-test
Ran 40 tests containing 77 assertions.
0 failures, 0 errors.
```
*Warning:* do not attempt to run these integration tests against an existing …
> Perms refactor

- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/views/widgets/PreferencesView.ui.xml
Adjust margins so that folder selector widget is not cut-off in firefox.
> CORE-7656 adjust margins.

- services/data-info/src/data_info/routes/avus.clj
- services/data-info/src/data_info/routes/domain/avus.clj
- services/data-info/src/data_info/services/metadata.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/routes/filesystem.clj
- services/terrain/src/terrain/services/filesystem/metadata.clj
Remove duplicate attribute checks and the corresponding `force` param
from the POST /data/{data-id}/metadata/copy endpoint.
Move path-count validation from the terrain endpoint and into data-info.
> CORE-7708 Remove dup attr checks from POST /data/{data-id}/metadata/copy

- services/anon-files/src/anon_files/serve.clj
Previously, we were returning what RFC 2616 specifically mentions is
incorrect (a Content-Range header with no last-byte-pos). Though RFC
7233 which supersedes it does not include that line, we have a perfectly
accurate count of the last byte we are returning, and should return it
since the Content-Range header is intended to specify what was returned,
not what was requested. Therefore, this sets the filesize as the upper
end of the range for unbounded requests.
I don't actually know how important this is, but I do believe the changed value is more correct!
> Provide accurate byte ranges in anon-files

- databases/de-database-schema/src/main/conversions/c270_2016061401.clj
- databases/de-database-schema/src/main/data/22_python_app.sql
- databases/de-database-schema/src/main/data/99_version.sql
- libs/kameleon/project.clj
We need to have a Python 2.7 tool and app that uses the time, memory, and cpu limits, so I've added one to be included with the DE when the database is init'ed. I've also included a conversion to add the same tool and app to existing databases.
The SQL for adding a new tool and app to the database is convoluted enough that I didn't want to add it to the existing data file, 21_internal_apps.sql.
This has been tested by init'ing a new database with the discoenv/unittest-dedb:dev image as well as by upgrading an existing database with the same image.
> Add a Python 2.7 tool and app to the database

- docker/nginx-consul-template/Dockerfile
- docker/nginx-consul-template/run-consul-template.sh
- docker/nginx-consul-template/run-nginx.sh
https://github.com/progrium/entrykit is designed for exactly what we're doing here, which is running two codependent processes inside a container.
It's a little bit stupid about quoting, so I'm still running two shell scripts so that I can actually have the quoting work properly, but this is much better than just running it with `&` and hoping for the best, in particular because this means our restart policies can be much more useful if the containers actually exit when nginx is dead.
> CORE-7713: switch nginx-consul-template to use entrykit

- databases/metadata/src/main/conversions/c270_2016061401.clj
- databases/metadata/src/main/data/99_version.sql
- databases/metadata/src/main/extensions/target_enum.sql
Allows AVUs in the metadata db to target other AVUs.
> CORE-7712 Add 'avu' enum to metadata database target_enum type.

- golang/src/dbutil/connector.go
- golang/src/permissions/clients/grouper/grouper.go
- golang/src/permissions/restapi/configure_permissions.go
- golang/src/saved-searches/main.go
- golang/src/tree-urls/main.go
`saved-searches` and `tree-urls` are often crashing upon startup when launched in our integration testing environment. This happens because these services start fast and often attempt to connect to Postgres before the database is ready. This change modifies both services so that they attempt to connect for a minute before giving up.
> Database Connection Retries

- services/metadata/project.clj
- services/metadata/src/metadata/routes/domain/template.clj
- services/metadata/src/metadata/routes/templates.clj
- services/metadata/src/metadata/services/templates.clj
- services/metadata/src/metadata/util/csv.clj
- services/terrain/src/terrain/clients/metadata/raw.clj
- services/terrain/src/terrain/routes/filesystem.clj
This adds four endpoints between metadata and terrain:
* `/templates/:template-id/blank-csv`: blank CSV file suitable for filling out and using for bulk upload
* `/templates:template-id/guide-csv`: guide to fields in the template, in CSV form
* `/secured/filesystem/metadata/template/:template-id/blank-csv` passing to the metadata blank-csv endpoint
* `/secured/filesystem/metadata/template/:template-id/guide-csv` passing to the metadata guide-csv endpoint
The metadata endpoints accept an `attachment` query parameter, which if set to false (default true) will exclude the "attachment" bit from the content-disposition, which makes it easier to see the output in swagger docs.
There's a corresponding gh-pages-metadata-template-csv branch documenting the terrain changes.
> CORE-7727, CORE-7728: metadata template blank/template CSV and guide CSV endpoints

- ui/de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/propertyEditors/DecimalInputPropertyEditor.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/propertyEditors/IntegerInputPropertyEditor.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/propertyEditors/TextInputPropertyEditor.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/integration/client/view/propertyEditors/widgets/ArgumentValidatorEditor.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/widgets/client/view/editors/arguments/converters/ArgumentEditorConverter.java
- ui/de-lib/src/main/java/org/iplantc/de/collaborators/client/views/ManageCollaboratorsViewImpl.java
CORE-7642 - This fixes a bug where validations added to an App (in particular for Integer ranges, Decimal ranges, and Text regex/max char which all use liststores) were not saved in the App Editor window.  There were two issues. First issue was that sometimes the validators in App Editor were never actually saved.  The second issue was that when a user went to launch the app, there was logic preventing the saved validators from ever being applied.
CORE-5906 - The static IDs in this ticket have all been validated previously except for the checkboxes in the grid in the Collaborators dialog. My assumption was that setting the IDs after the dialog had been shown (show method) would be sufficient, but since the checkboxes are inside the grid you have to wait to set the IDs after the grid …
> CORE-7642 and CORE-5906

- ui/de-lib/src/main/java/org/iplantc/de/client/services/converters/NotificationCallbackConverter.java
- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/DesktopPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/desktop/client/presenter/util/NotificationUtil.java
When user is logged in, after launching a job (or receive some form of notification), clicking on the notification did not open corresponding windows. This was result of websocket implementation code not setting up context after it receives a notification. Added logic to fix that issue.
> CORE-7730 fix notification context click.

- libs/common-swagger-api/src/common_swagger_api/schema/ontologies.clj
Updated common-swagger-api.schema.ontologies/OntologyDetails to allow null `iri` fields.
This prevents `ERR_SCHEMA_VALIDATION` errors when uploading an ontology XML document that does not define the ontology's IRI.
Storing the ontology with a null IRI should not break any other functionality, since a unique ontology version is still created by the metadata service that's used in all other endpoints.
> CORE-7741 Allow null ontology IRI’s in metadata responses.

- ansible/playbooks/de-deploy-services.yaml
(in de-deploy-services.yaml)
This is to accommodate the new split in prod. There's also a branch in private ansible named after the new server.
This branch, and that, are against their respective beta branches since we'll want them for release on Tuesday.
> Split job-status-to-apps-adapter and job-status-recorder into their own hostgroups

- databases/metadata/src/main/conversions/c270_2016062401.clj
- databases/metadata/src/main/data/99_version.sql
- databases/metadata/src/main/tables/ontologies.sql
- libs/kameleon/project.clj
A deleted flag won't be necessary for the `ontology_classes` or `ontology_hierarchies` tables.
A hierarchy will be deleted directly, which will delete the associated `ontology_classes` (and `ontology_hierarchies` by cascade).
They can easily be added back with the "save hierarchies" endpoint, which will add the exact same classes and hierarchies under a hierarchy root, parsed from the saved ontology in the `ontologies` table.
> CORE-7745 Add deleted flag to metadata db ontologies table.

- libs/iplant-clojure-commons/src/clojure_commons/exception_util.clj
- libs/metadata-client/src/metadata_client/core.clj
- services/apps/src/apps/routes/admin.clj
- services/apps/src/apps/service/apps/de/admin.clj
- services/metadata/src/metadata/persistence/ontologies.clj
- services/metadata/src/metadata/routes/ontologies.clj
- services/metadata/src/metadata/services/ontology.clj
- services/terrain/src/terrain/clients/apps/raw.clj
- services/terrain/src/terrain/clients/metadata/raw.clj
- services/terrain/src/terrain/routes/metadata.clj
These changes allow an admin to mark an ontology as deleted (so it no longer displays in the ontology listing), and to delete all classes under an ontology hierarchy for a given `ontology-version`.
This will allow the admin to add an ontology hierarchy root, and then selectively remove sub-hierarchies, or the entire hierarchy from the root.
Classes and sub-hierarchies removed with the new endpoint can easily be re-added by re-saving the hierarchy root with the `PUT /admin/ontologies/{ontology-version}/{root-iri}` endpoint (it will only save classes and hierarchies that are not already saved under the given root).
* `DELETE /admin/ontologies/{ontology-version}`
* `DELETE /admin/ontologies/{ontology-version}/{root-iri}`
* `DELETE /admin/ontologies/{ontology-version}`
* Returns an error if …
> CORE-7746 Add metadata admin DELETE ontology and hierarchy endpoints.

- services/data-info/src/data_info/routes/domain/trash.clj
This changes the schema to use OptionalPaths rather than Paths, since
that makes the key optional but more importantly allows the list of
paths to be empty.
n.b. I don't have any huge preference that this go directly into master, though it is an annoying thing which was reported by a user, so it might be good to have this be a hotfix. Perhaps it should go into beta rather than dev, but not right into master? I'd love to hear thoughts!
> CORE-7758: schema validation when emptying an already-empty trash

- databases/metadata/src/main/conversions/c280_2016070501.clj
- databases/metadata/src/main/data/99_version.sql
- databases/metadata/src/main/tables/templates.sql
- libs/kameleon/project.clj
Adds metadata db conversion 2.8.0:20160705.01 and updates the metadata db SQL init scripts.
> CORE-7760 Add ‘description’ column to metadata ‘templates’ table.

- services/metadata/src/metadata/persistence/templates.clj
- services/metadata/src/metadata/routes/schemas/template.clj
Allows admins to add metadata templates with descriptions, update descriptions for existing templates, and allows template listing and detail endpoints to return the description.
(Should not be merged before #262)
> CORE-7761 Add ‘description’ field to metadata template CRUD endpoints.

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/events/AddMetadataSelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/events/DeleteMetadataSelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/events/EditMetadataSelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/presenter/MetadataTemplatesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/EditMetadataTemplateViewImpl.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/MetadataTemplateProperties.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/TemplateListingView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/metadata/view/TemplatesListingViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/shared/Belphegor.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/diskResources/MetadataTemplateInfo.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/metadata/DefaultEditMetadataTemplateViewAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/metadata/DefaultTemplateListingAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/metadata/MetadataDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/metadata/MetadataDisplayStrings.properties
This PR addresses a request for there to be a limit on how long the name of a metadata template can be (20 chars) and also adds an optional description field.  The metadata template names currently are too long because the description is also being included in the name.
I noticed some NPEs happening when clicking on the Edit and Delete buttons so I patched those up.  Then I noticed that the view was calling presenter methods directly, so I went ahead and refactored the view to fire events instead.
> CORE-7762 Update metadata templates in Belphegor with 'description' field and name limit

- services/apps/src/apps/persistence/app_metadata.clj
- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/routes/schemas/app.clj
- services/apps/src/apps/service/apps/de/metadata.clj
The `/apps/:id/publish` endpoint now accepts a list of AVUS instead of category IDs, which it will publish immediately to the metadata service.
This means apps published by users are categorized immediately into the ontology hierarchies the user chooses, rather than requiring admins to categorize the apps.
* This also makes the `suggested_groups` table obsolete, and it can be removed in a future db conversion.
* In a following PR, this endpoint will also tag the app with a "Beta" AVU, which will be the indicator to users that the app has not been curated by the admins yet.
> CORE-7773 Save AVUS instead of category IDs in apps publish endpoint.

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/SubmitAppForPublicUseView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/submit/SubmitAppForPublicPresenter.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/submit/SubmitAppForPublicUseView.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/submit/SubmitAppForPublicUseViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/apps/AppAutoBeanFactory.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/apps/PublishAppRequest.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/AppUserServiceFacade.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/AppUserServiceFacadeImpl.java
These are the UI changes that go along with PR #273.  Basically, since we're moving away from app categories, when a user wants to publish an app, they now have the active ontology's hierarchies to choose from to categorize their app.  Those hierarchies then get turned into AVUs for metadata.
> CORE-7645 Update Public Submission Form for Ontology Hierarchies

- services/metadata/project.clj
- services/metadata/src/metadata/routes/templates.clj
- services/metadata/src/metadata/services/templates.clj
- services/terrain/src/terrain/clients/metadata/raw.clj
- services/terrain/src/terrain/routes/filesystem.clj
Plus, some refactoring. Mostly just making it so we don't hit the database multiple times for this endpoint which does several things with the same template data.
This uses a sanitize-filename library I found to generate the folder name inside the zip file from the template name. It seems to be pretty sane, though it does choose to replace slashes with dollar signs which could be mildly confusing. Still, it should be pretty readable in general. For making zip files, apparently `me.raynes.fs` has tools for this already! Woo!
> CORE-7755: download zip of blank+guide template CSVs

- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/routes/apps/categories.clj
- services/apps/src/apps/routes/schemas/app.clj
- services/apps/src/apps/service/apps/de/listings.clj
The `/apps/`, `/apps/categories/:id`, and `/apps/hierarchies/:iri/apps` endpoints now include a `beta` flag for each app, which is `true` for apps that have the `beta` metadata AVU attached.
> CORE-7935 Update apps listing endpoints to include a beta flag.

- libs/clj-jargon/project.clj
- libs/clj-jargon/src/clj_jargon/metadata.clj
Jargon 4.0.2.6 has been released, which includes my fixes for the AVU query code, so we can now return to the code I'd previously written for AVU lookups by specific attributes and values, which is more efficient.
> CORE-7677: upgrade jargon version and return to using AVU query code

- ansible/roles/util-cfg-service/templates/apps.properties.j2
- services/apps/src/apps/persistence/app_metadata.clj
- services/apps/src/apps/service/apps/de/admin.clj
- services/apps/src/apps/service/apps/de/categorization.clj
- services/apps/src/apps/service/apps/de/edit.clj
- services/apps/src/apps/service/apps/de/metadata.clj
- services/apps/src/apps/service/apps/de/validation.clj
- services/apps/src/apps/util/config.clj
Since the Beta category is going away with all the old app categories, when an app is made public from now on, it will be "tagged" with a "Beta" AVU, rather than added to the old Beta category.
These changes remove references in the apps service to the old apps.workspace.beta-app-category-id config and add new settings for the beta AVU’s attr, value, and the attr's label.
These new configs are used to automatically add the beta AVU to apps published with the `/apps/:id/publish` endpoint.
> CORE-7934 Update publish endpoint to include beta AVU in app metadata.

- services/iplant-groups/src/iplant_groups/clients/grouper.clj
- services/iplant-groups/src/iplant_groups/service/format.clj
- services/iplant-groups/src/iplant_groups/util/config.clj
- services/iplant-groups/src/iplant_groups/util/service.clj
This should just be consistent with other such exception handling updates.
> CORE-7261: update iplant-groups exception handling to match other services

- libs/clj-jargon/src/clj_jargon/tickets.clj
I didn't test my changes in #139 well enough, clearly, since it didn't actually work at all :confounded: 
I've also added some debug-level logging, which won't appear in most cases but could hopefully be useful for other debugging in the future.
> Use the correct name in the context map for preventing temporary password creations

- services/NotificationAgent/src/notification_agent/db.clj
This happened to be erroring in a QA environment, I think for unrelated reasons, but I think it's better to be explicit about the columns we're inserting into.
So, minor, but may as well be fixed. I'd like a double-check that I've put the right columns in the right order, though.
> Use explicit column names in a notificationagent insert statement

- ansible/inventories/example.cfg
- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/dewey.properties.j2
- ansible/roles/util-cfg-service/templates/infosquito.properties.j2
- ansible/roles/util-cfg-service/templates/monkey.properties.j2
- ansible/roles/util-cfg-service/templates/templeton-incremental.yaml.j2
- ansible/roles/util-cfg-service/templates/templeton-periodic.yaml.j2
- ansible/roles/util-cfg-service/templates/terrain.properties.j2
The current host groups which call out the hosts which host elasticsearch clusters for our data-store- clusters are in the `[elasticsearch]` host groups. 
Currently, the DE only runs one cluster, but we cannot preclude that we might run multiple clusters in the future. 
Therefore, it is desirable to separate variables related to accessing the data-store- clusters from variables related to the installation of elasticsearch.
Variables related to elasticsearch installation are kept in the private ansible repo.
> Core 8087 - Ansible Elasticsearch host/group refactoring

- services/anon-files/project.clj
- services/anon-files/src/anon_files/serve.clj
We weren't URL decoding... well, anything, in anon-files. So this would probably have also failed with other url-unsafe characters that'll end up in the URI as decoded.
Tested this manually and it does work with the test file listed in the ticket.
> DE-1133/CORE-8094: handle spaces in paths in anon-files properly

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/grid/cells/AppNameCell.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/apps/App.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/apps/AdminAppNameCellDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppNameCell.css
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppNameCellDefaultAppearance.java
This applies to both Belphegor and the DE.  Belphegor just doesn't have the underlined hyperlink app names.
> CORE-7898 Make apps tagged as Beta appear as blue

- ansible/roles/util-cfg-service/templates/apps.properties.j2
- libs/metadata-client/src/metadata_client/core.clj
- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/routes/schemas/app.clj
- services/apps/src/apps/service/apps/de/listings.clj
- services/apps/src/apps/util/config.clj
- services/metadata/src/metadata/persistence/avu.clj
- services/metadata/src/metadata/routes/ontologies.clj
- services/metadata/src/metadata/routes/schemas/ontologies.clj
- services/metadata/src/metadata/services/ontology.clj
These changes update the `/apps/:id/details` endpoint to include a `hierarchies` field, populated by a new metadata service `POST /ontologies/{ontology-version}/filter` endpoint, which returns all hierarchies the given target is tagged under.
> CORE-8090: Update apps details endpoint to include an app's category hierarchy

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/AppDetailsView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/events/selection/DetailsCategoryClicked.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/events/selection/DetailsHierarchyClicked.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/gin/factory/AppDetailsViewFactory.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/details/AppDetailsViewPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/details/AppDetailsViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/details/AppDetailsViewImpl.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/details/dialogs/AppDetailsDialog.java
- ui/de-lib/src/main/java/org/iplantc/de/client/models/apps/App.java
- ui/de-lib/src/main/java/org/iplantc/de/client/util/OntologyUtil.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/details/AppDetailsDefaultAppearance.java
- ui/de-lib/src/test/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImplTest.java
Since we're moving to hierarchies in 2.8, the app details window has become cluttered with the list of all the paths where an app can be found.  Instead of having a textual path in the app details window, we will have a slimmed down tree to show only the hierarchies where the app resides.
If the app is an HPC app, the details window will show a tree that only has the HPC category.
If the app has not been tagged with any hierarchies, only the Unclassified hierarchies will be listed.
Additionally, clicking on any node in the tree will open up that hierarchy in the Apps window automatically.
> CORE-8091 Switch to tree paths in AppDetails view

- libs/metadata-client/src/metadata_client/core.clj
- services/apps/src/apps/metadata/avus.clj
- services/apps/src/apps/persistence/app_metadata.clj
- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/service/apps/de.clj
- services/apps/src/apps/service/apps/de/admin.clj
- services/apps/src/apps/service/apps/de/categorization.clj
- services/apps/src/apps/service/apps/de/edit.clj
- services/apps/src/apps/service/apps/de/listings.clj
- services/apps/src/apps/service/apps/de/validation.clj
- services/metadata/src/metadata/routes/avus.clj
- services/metadata/src/metadata/routes/schemas/avus.clj
- services/metadata/src/metadata/services/avus.clj
These changes update the apps service to validate duplicate app names under ontology hierarchies.
The metadata `POST /avus/filter-targets` endpoint now accepts a list of AVUs (just attr/value pairs for now) rather than a single `attr` and `value`.
The following app edit endpoints now validate duplicate app names in the app's current ontology hierarchy:
* PATCH /admin/apps/:app-id
* PATCH /apps/:app-id
* PUT /apps/:app-id
The following app metadata endpoints now validate duplicate app names in ontology hierarchy AVUs given in the request:
* POST /apps/:app-id/metadata
* PUT /apps/:app-id/metadata
> CORE-8084 Add duplicate app name validation for ontology hierarchies

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/AppToOntologyHierarchyDND.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologyHierarchyToAppDND.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologiesViewDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.properties
Once Agave apps are tagged with EDAM ontology terms, agave apps will get listed in the admin App Catalog tab mixed in with DE apps.  This PR makes sure that app categorization is disabled for the admins on any of those external apps.
> CORE-7927 Disable actions in App Catalog for external apps

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/ui/de.properties.j2
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/OntologyHierarchiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/util/OntologyUtil.java
- ui/de-lib/src/main/java/org/iplantc/de/shared/DEProperties.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologiesViewDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/hierarchies/OntologyHierarchiesDefaultAppearance.java
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImplTest.java
- ui/de-lib/src/test/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImplTest.java
- ui/de-lib/src/test/java/org/iplantc/de/client/util/OntologyUtilTest.java
This updates the UI so that instead of hard-coding the attribute values for metadata into the UI, the UI can read the mapping between IRIs and the corresponding attribute from the configs.  The value is the attribute and the key is a regex that should match all IRIs that should be associated with that attribute.  Right now the UI needs to know which attributes apply to which hierarchies in order to update any metadata.
[This is a temporary solution until changes can be made so that admins can select which attributes they want associated with which hierarchies, which would be too many changes to make the 2.8 release.]
> CORE-8114 Update Apps window to parse ontology attrs from configs

- services/iplant-groups/src/iplant_groups/clients/grouper.clj
- services/iplant-groups/src/iplant_groups/routes/schemas/params.clj
- services/iplant-groups/src/iplant_groups/routes/subjects.clj
- services/iplant-groups/src/iplant_groups/service/subjects.clj
This is in preparation for fetching groups for a subject when an analysis is submitted -- we want to only fetch groups which are within the folder corresponding to the current environment, then remove the environment-folder part of the name and pass it down to jex-adapter.
> CORE-8126 prep: support fetching groups for a subject with a folder filter in iplant-groups

- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/test/integration.clj
- services/terrain/test/integration/terrain/services/permanent_id_requests.clj
This fixes the terrain permanent-id-requests service's expected format of data-info's metadata endpoint response (the metadata AVUs are no longer nested under a `metadata` key, after one of the last commits of #196).
Initial integration tests have also been added for terrain.services.permanent-id-requests, with more to be added before merging this PR.
> CORE-8102 Fix terrain's Permanent ID Requests metadata parsing

- services/apps/src/apps/clients/iplant_groups.clj
- services/apps/src/apps/service/apps/de/jobs/common.clj
This time actually fixing the ticket! This:
* adds a client function for fetching a subject's groups
* adds a client function for trimming off the environment name
* uses them to add information to the submission that will be sent to the jex in the format I was told to
I've tried this against our dev environment with the newly-deployed jex-adapter and the `+IpcUserGroups` entry I'd expect (`{"users:de-users"}` only -- I'm not in anything else) appeared.
> CORE-8126: put user groups into the jex submission in apps

- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/schemas/data.clj
- services/data-info/src/data_info/services/uuids.clj
- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
This endpoint uses more direct methods for getting the UUID, for cases
where a full stat entry isn't needed, just the path. Terrain has also
been updated to use this for the data-info client's uuid-for-path
function, which is used for a lot of terrain's current translating of
paths into uuids.
Ideally, this eventually goes away or nearly away as we move the UI to
use data UUIDs in more/most places, such that terrain doesn't need to be
making these lookups. But, for now, this should trim off a decent amount
off each request it has to make to resolve a UUID.
I've put this up for review since it adds an endpoint, and filed an issue at CORE-8129 to track for QA's sake.
> Create optimized uuid-for-path endpoint in data-info

- services/data-info/src/data_info/services/create.clj
- services/data-info/src/data_info/services/directory.clj
- services/data-info/src/data_info/services/entry.clj
- services/data-info/src/data_info/services/exists.clj
- services/data-info/src/data_info/services/filetypes.clj
- services/data-info/src/data_info/services/home.clj
- services/data-info/src/data_info/services/manifest.clj
- services/data-info/src/data_info/services/metadata.clj
- services/data-info/src/data_info/services/page_file.clj
- services/data-info/src/data_info/services/page_tabular.clj
- services/data-info/src/data_info/services/permissions.clj
- services/data-info/src/data_info/services/rename.clj
- services/data-info/src/data_info/services/root.clj
- services/data-info/src/data_info/services/sharing.clj
- services/data-info/src/data_info/services/stat.clj
- services/data-info/src/data_info/services/tickets.clj
- services/data-info/src/data_info/services/trash.clj
- services/data-info/src/data_info/services/users.clj
- services/data-info/src/data_info/services/uuids.clj
- services/data-info/src/data_info/services/write.clj
- services/data-info/src/data_info/util/irods.clj
NOTE: most of this PR is indentation changes. I'd recommend adding `w=1` to the URL to exclude those lines.
This adds a macro which is intended for wrapping `with-jargon` and which catches `JargonException`s and adds some extra info/a sensible error code when the error is an `IOException`, which I believe should be what happens in these cases (and, hopefully, not in other cases). When it catches these errors, the error that comes out looks like: 
```json
{
"error_code": "ERR_UNAVAILABLE",
"reason": "iRODS is unavailable: org.irods.jargon.core.exception.JargonException: java.net.UnknownHostException: ..."
}
```
(UnknownHostException is a type of IOException)
I'm not that happy with this right now because of how many changes it seems to require. But, I'm not happy with putting it into …
> CORE-8110: add a wrapping macro to catch IOExceptions thrown as JargonExceptions in data-info

- ansible/roles/util-cfg-service/templates/apps.properties.j2
- services/apps/src/apps/clients/email.clj
- services/apps/src/apps/service/apps/de/admin.clj
- services/apps/src/apps/util/config.clj
- services/iplant-email/conf/app_deletion_notification.st
These changes update the apps service `DELETE /admin/apps/{app-id}` endpoint to send an app deletion notification email to the app integrator.
The email template `app_deletion_notification.st` was added to the iplant-email service for this notification.
The following apps configs were also added:
* apps.email.base-url
* apps.email.app-deletion.from
* apps.email.app-deletion.subject
* apps.ui.base-url
> CORE-8103 Notify integrator when admin deletes app

- libs/kameleon/src/kameleon/app_listing.clj
- libs/metadata-client/src/metadata_client/core.clj
- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/service/apps/de/listings.clj
- services/metadata/src/metadata/persistence/avu.clj
- services/metadata/src/metadata/persistence/ontologies.clj
- services/metadata/src/metadata/routes/ontologies.clj
- services/metadata/src/metadata/routes/schemas/ontologies.clj
- services/metadata/src/metadata/services/avus.clj
- services/metadata/src/metadata/services/ontology.clj
This PR updates the /apps search endpoint to also search apps by category name.
So the search endpoint should still include the same search results as before, but now it will also include apps with ontology class AVUs attached whose label matches the search term (using the same wildcard logic to match the search term in other app fields).
The /apps search endpoint uses a new metadata service `POST /ontologies/{ontology-version}/filter-targets` endpoint to search apps with matching category labels to include in the /apps search results.
> CORE-8128: Update /apps search endpoint to also search by category name

- services/apps/src/apps/persistence/jobs.clj
This should stop the UI from throwing an error when you try to sort by this column!
> CORE-8133: add :username sort to analyses translate-sort-field

- ui/de-lib/src/main/java/org/iplantc/de/admin/apps/client/AdminAppsGridView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/apps/client/views/grid/AdminAppsGridImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/events/PreviewHierarchySelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/events/RefreshPreviewButtonClicked.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/gin/factory/OntologiesViewFactory.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/service/OntologyServiceFacade.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/service/impl/OntologyServiceFacadeImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/AppToOntologyHierarchyDND.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologyHierarchyToAppDND.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologiesViewDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.properties
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImplTest.java
The App Catalog tab was initially created to serve the transition period from 2.7 to 2.8 where the science team was tagging apps from the old app categories into the new ontology hierarchies.
This PR updates the App Catalog tab into a state where you no longer see the old app categories, instead you get a "preview" of what hierarchies the DE users would see.  Basically now the admins can edit an ontology and have a side-by-side "preview" of that ontology in the DE (which is basically the filtered-down list of hierarchies).
> CORE-8125 Switch to DE hierarchy preview instead of AppCategory listing in App Catalog tab

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/ui/de.properties.j2
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/events/RestoreAppButtonClicked.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/client/services/AppServiceFacade.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/AppUserServiceFacadeImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/client/util/OntologyUtil.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologiesViewDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/ontologies/OntologyDisplayStrings.properties
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImplTest.java
This PR enables the admin to restore apps that have been deleted in Belphegor.  This is done by adding a fake hierarchy called "Trash".  Clicking on that hierarchy fetches the list of deleted apps.  From there, the admin can select a deleted app and restore the app using the Restore button.
> CORE-8112 Add ability to restore apps within App Catalog tab in Belphegor

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/grid/cells/AppNameCell.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/admin/apps/AdminAppNameCellDefaultAppearance.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/AppsMessages.properties
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppNameCell.css
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/apps/cells/AppNameCellDefaultAppearance.java
This PR is to address an issue where private apps might have the same name as public apps, which could be confusing for users to figure out which app they intended to use.
Private apps will now be green.
Also, this makes sure that beta apps (blue) and private apps (green) are the same size font as public apps (they were slightly smaller).
> CORE-7644 Show non-public apps with green text

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorView.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorViewImpl.java
This is getting rid of the Apps tab in Belphegor and not initializing the Apps presenter.  
Removing the old apps code will be a PR for another time 😄
> CORE-8111 Visually removing the App tab from Belphegor

- services/apps/src/apps/persistence/app_metadata.clj
- services/apps/src/apps/service/apps/de/listings.clj
This change updates the `GET /apps/hierarchies/{root-iri}` and `GET /admin/ontologies/{ontology-version}/{root-iri}` endpoints to filter out hierarchies which only contain deleted apps.
> CORE-8134 Filter hierarchies for deleted apps.

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/OntologiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/events/HierarchySelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/events/PreviewHierarchySelectedEvent.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/AppCategorizeViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/ontologies/views/OntologiesViewImpl.java
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/ontologies/presenter/OntologiesPresenterImplTest.java
Currently, if you click on the Trash category in the App Catalog tab, both the editor grid and the preview grid get masked when only the editor grid should get masked.
Also, when you try to categorize an app, the Trash category is listed when it should not be.  Deleting an app should be done through either drag-and-drop to the Trash category or clicking the Delete App button.
I also renamed TreeType to ViewType (most of the modifications in this PR), since I needed a way to choose which grid to mask and selecting the grid based on a "TreeType" did not make sense.
> CORE-8112 Loading mask fix for App Catalog and Categorize dialog fix

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/workshopAdmin/presenter/WorkshopAdminPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/workshopAdmin/view/WorkshopAdminViewImpl.java
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/workshopAdmin/presenter/WorkshopAdminPresenterImplTest.java
- ui/de-lib/src/test/java/org/iplantc/de/admin/desktop/client/workshopAdmin/view/WorkshopAdminViewImplTest.java
Some small mods to the WorkAdmin code in order to get Mockito to be happy.
I couldn't get Mockito to properly test the methods within the inner event handler classes.  If we later decide to refactor to implementing the event handler interfaces in the presenter, then we can add tests for those handler methods as well.
> CORE-8130 Add Workshop Admin tests

- services/apps/src/apps/metadata/reference_genomes.clj
When attempting to rename or update the path of a reference genome, the `PATCH /admin/reference-genomes/` endpoint would return an error like
```json
{"error_code":"ERR_EXISTS","reason":"Another reference genome with the given name already exists."}
```
The `not=` symbol needs to be quoted when used outside of the korma `where` macro.
Otherwise the path and name validation conditionals were parsed as queries like
```sql
WHERE (? AND "genome_reference"."path" = ?)
```
which always found a match when attempting to update just the path or name of an existing reference genome.
Also removed the unused `apps.metadata.reference-genomes/get-all-reference-genomes` function.
> CORE-7544 Fix reference genome path/name validation.

- services/apps/src/apps/service/apps/job_listings.clj
- services/apps/src/apps/service/apps/jobs/permissions.clj
- services/apps/src/apps/service/apps/jobs/sharing.clj
`supports-job-sharing?` was changed in 0e5aae1abac55d609d51b6070307f0e5b1e8fd64 to take a list of job steps rather than a job ID, but not all of the places it was called were updated.
This adds another function which does the lookup of job steps from job ID that the old function did, and renames both functions to be more descriptive, updating their call sites as appropriate.
> CORE-8155: fix call signatures for job sharing validations

- libs/clj-icat-direct/src/clj_icat_direct/icat.clj
- libs/clj-icat-direct/src/clj_icat_direct/queries.clj
PostgreSQL is rubbish at predicting the number of rows for CTE Scans, which goes really badly when the answer is 16000 and it guesses 25.
It doesn't have this issue with temporary tables being created instead, so this does that.
> Use temporary tables rather than CTEs to speed up certain paged directory listing queries
