cyverse/DE

- ansible/roles/elk-elasticsearch/templates/elk-elasticsearch.service
- ansible/roles/elk-kibana/templates/elk-kibana.service
- ansible/roles/elk-logstash/templates/elk-logstash.service
- ansible/roles/grouper/templates/grouper-nginx.service
- ansible/roles/grouper/templates/iplant-grouper.service
- ansible/roles/jex/templates/jex.service
- ansible/roles/logstash-forwarder/templates/logstash-forwarder.service
- ansible/roles/services/templates/anon-files.service
- ansible/roles/services/templates/clockwork.service
- ansible/roles/services/templates/condor-log-monitor.service
- ansible/roles/services/templates/data-info.service
- ansible/roles/services/templates/dewey.service
- ansible/roles/services/templates/exim-sender.service
- ansible/roles/services/templates/info-typer.service
- ansible/roles/services/templates/infosquito.service
- ansible/roles/services/templates/iplant-email.service
- ansible/roles/services/templates/iplant-groups.service
- ansible/roles/services/templates/jex-events.service
- ansible/roles/services/templates/kifshare.service
- ansible/roles/services/templates/metadactyl.service
- ansible/roles/services/templates/metadata.service
- ansible/roles/services/templates/monkey.service
- ansible/roles/services/templates/notification-agent.service
- ansible/roles/services/templates/saved-searches.service
- ansible/roles/services/templates/terrain.service
- ansible/roles/services/templates/tree-urls.service
- ansible/roles/services/templates/user-preferences.service
- ansible/roles/services/templates/user-sessions.service
- ansible/roles/ui/templates/de-ui-nginx.service
- ansible/roles/ui/templates/de-ui.service
> CORE-7245 - Improved systemd service restart policies

- ansible/roles/de-update-database/meta/main.yaml
- ansible/roles/util-pgpass/tasks/main.yaml
- ansible/roles/util-pgpass/templates/postgres.pgpass.j2
From a monster pull request to a mini pull request. :smile:
> CORE-7417: add a separate role to generate .pgpass files

- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/presenter/NotificationPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/views/NotificationToolbarView.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/views/NotificationToolbarViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/views/NotificationView.java
- ui/de-lib/src/main/java/org/iplantc/de/notifications/client/views/NotificationViewImpl.java
Added method to enable/disable Delete All notifications button
Added listStore size check on grid refresh to determine if DeleteAll button should be enabled
> CORE-4831 Add logic to enable/disable Notification's DeleteAll btn

- services/apps/src/apps/clients/iplant_groups.clj
- services/apps/src/apps/protocols.clj
- services/apps/src/apps/routes/apps.clj
- services/apps/src/apps/routes/domain/permission.clj
- services/apps/src/apps/service/apps.clj
- services/apps/src/apps/service/apps/agave.clj
- services/apps/src/apps/service/apps/combined.clj
- services/apps/src/apps/service/apps/de.clj
- services/apps/src/apps/service/apps/de/listings.clj
- services/apps/src/apps/service/apps/de/permissions.clj
- services/apps/src/apps/service/util.clj
- services/terrain/src/terrain/clients/apps/raw.clj
- services/terrain/src/terrain/routes/metadata.clj
These are the changes to implement the app permission listing service.
> Sharing services

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/terrain.properties.j2
- services/data-info/src/data_info/services/create.clj
- services/data-info/src/data_info/services/rename.clj
- services/data-info/src/data_info/services/trash.clj
- services/data-info/src/data_info/util/paths.clj
- services/metadata/src/metadata/persistence/permanent_id_requests.clj
- services/metadata/src/metadata/routes.clj
- services/metadata/src/metadata/routes/domain/common.clj
- services/metadata/src/metadata/routes/domain/permanent_id_requests.clj
- services/metadata/src/metadata/routes/permanent_id_requests.clj
- services/metadata/src/metadata/services/permanent_id_requests.clj
- services/terrain/src/terrain/clients/data_info.clj
- services/terrain/src/terrain/clients/metadata/raw.clj
- services/terrain/src/terrain/core.clj
- services/terrain/src/terrain/routes/permanent_id_requests.clj
- services/terrain/src/terrain/services/filesystem/validators.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/config.clj
See previous comments in https://github.com/cyverse/DE/pull/30
> Add Permanent ID request CRUD service endpoints

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/terrain.properties.j2
- libs/iplant-clojure-commons/src/clojure_commons/exception.clj
- services/terrain/src/terrain/clients/ezid.clj
- services/terrain/src/terrain/routes/permanent_id_requests.clj
- services/terrain/src/terrain/services/admin.clj
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/config.clj
See previous comments in https://github.com/cyverse/DE/pull/31
> Add admin EZID submission service endpoints

- ansible/inventories/group_vars/all
- ansible/roles/util-cfg-service/templates/terrain.properties.j2
- services/iplant-email/conf/permanent_id_request.st
- services/iplant-email/conf/permanent_id_request_complete.st
- services/terrain/src/terrain/services/permanent_id_requests.clj
- services/terrain/src/terrain/util/config.clj
- services/terrain/src/terrain/util/email.clj
See previous comments in https://github.com/cyverse/DE/pull/32
> Add Permanent ID Request notifications

- services/data-info/src/data_info/routes/data.clj
- services/data-info/src/data_info/routes/domain/data.clj
- services/data-info/src/data_info/services/create.clj
- services/data-info/src/data_info/services/write.clj
- services/data-info/src/data_info/util/validators.clj
- services/terrain/src/terrain/clients/data_info/raw.clj
- services/terrain/src/terrain/services/fileio/actions.clj
- services/terrain/src/terrain/services/fileio/controllers.clj
This builds on top of #38, which means it's probably better to review that first. The changes in this PR, from that one, are all in the most-recent commit, should you be reviewing it before that one's merged (at which point this PR should no longer show those changes).
> CORE-6213: migrate /secured/fileio/saveas

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/submit/SubmitAppForPublicUseViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/analyses/cells/AnalysisParamValueCell.css
There are two commits here.  One for each ticket.
> Core 3833 and Core 5472

- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilder.java
- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/SearchServiceFacadeImpl.java
- ui/de-lib/src/test/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilderTest.java
Please review my changes for changes.
> CORE-6052 fix search to exclude-include trash using query parameter.

- services/terrain/src/terrain/services/permanent_id_requests.clj
This validation fix should be required for the 2.4 release.
> CORE-7481 Fix Permanent ID Request metadata validations.

- services/terrain/src/terrain/services/permanent_id_requests.clj
This validation should be required for the 2.4 release.
> CORE-7489 Add PermID Request empty-folder validation.

- ui/de-lib/src/main/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilder.java
- ui/de-lib/src/test/java/org/iplantc/de/client/services/impl/DataSearchQueryBuilderTest.java
Please review my changes to fix advanced search when searching on owned by field.
> CORE-7490 fix data advanced search when search using owned by field.

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImpl.java
- ui/de-lib/src/test/java/org/iplantc/de/apps/client/views/toolBar/AppsViewToolbarImplTest.java
Please review UI changes for this issue.
> CORE-7494 allow app owners to edit their public app.

- services/jobservices/src/configurate/configurate.go
- services/jobservices/src/logcabin/logcabin.go
- services/jobservices/src/messaging/amqp.go
- services/jobservices/src/road-runner/main.go
Added some of the documentation from PR #101 and the `jobservices/README.md` which described the packages to the package-level documentation.
> Added package-lvl docs to jobservices

- services/apps/src/apps/clients/data_info.clj
- services/apps/src/apps/clients/iplant_groups.clj
- services/apps/src/apps/clients/notifications.clj
- services/apps/src/apps/clients/notifications/common_sharing.clj
- services/apps/src/apps/clients/notifications/job_sharing.clj
- services/apps/src/apps/protocols.clj
- services/apps/src/apps/routes/analyses.clj
- services/apps/src/apps/routes/domain/permission.clj
- services/apps/src/apps/service/apps.clj
- services/apps/src/apps/service/apps/agave.clj
- services/apps/src/apps/service/apps/combined.clj
- services/apps/src/apps/service/apps/de.clj
- services/apps/src/apps/service/apps/de/permissions.clj
- services/apps/src/apps/service/apps/jobs.clj
- services/apps/src/apps/service/apps/jobs/permissions.clj
- services/apps/src/apps/service/apps/jobs/sharing.clj
- services/apps/src/apps/service/apps/jobs/util.clj
- services/terrain/src/terrain/clients/apps/raw.clj
- services/terrain/src/terrain/routes/metadata.clj
...and the POST /analyses/unsharing endpoint.
> Add the POST /analyses/sharing endpoint

- ansible/inventories/example.cfg
- ansible/inventories/group_vars/all
- ansible/playbooks/de-pull-images.yaml
- ansible/playbooks/de-rm-containers.yml
- ansible/playbooks/de-start-containers.yml
- ansible/playbooks/de-stop-containers.yml
- ansible/playbooks/local-services-cfg.yml
- ansible/roles/de-services-cfg/meta/main.yaml
- ansible/roles/util-cfg-service/templates/metadata.properties.j2
- ansible/roles/util-cfg-service/templates/templeton-incremental.yaml.j2
- services/metadata/project.clj
- services/metadata/src/metadata/amqp.clj
- services/metadata/src/metadata/services/avus.clj
- services/metadata/src/metadata/util/config.clj
- services/templeton/src/messaging/amqp.go
- services/templeton/src/templeton/elasticsearch/elasticsearch.go
- services/templeton/src/templeton/main.go
- services/templeton/src/templeton/model/model.go
These two commits add the handling for incremental update messages (sent on the `de` exchange with routing key `metadata.update` and a JSON body with 'entity' and 'author' keys) as well as adds the code to the metadata service to publish these messages.
> CORE-7497: Templeton: incremental mode

- golang/docker-build-user-preferences.sh
- golang/src/user-preferences/main.go
- golang/src/user-preferences/main_test.go
- golang/user-preferences.docker
This is similar to the user-sessions rewrite. It even has the same flaws :smiling_imp: 
There are user-preferences branches for the internal scm and ansible repos, as well.
> Rewrite user-preferences in Go

- golang/src/templeton/elasticsearch/elasticsearch.go
Just a minor tweak, really. We'll want this once we're merging any metadata for stuff that isn't files or folders, e.g. for app catalog refresh work.
> Templeton: don't index things if the avu's TargetType isn't something we know how to index (a file or folder, for now)

- golang/src/condor-launcher/condor.go
- golang/src/condor-launcher/condor_test.go
- golang/src/condor-launcher/stops.go
- golang/src/condor-launcher/stops_test.go
- golang/src/configurate/configurate.go
- golang/src/configurate/configurate_test.go
- golang/src/de-job-killer/main.go
- golang/src/dockerops/containers.go
- golang/src/dockerops/containers_test.go
- golang/src/image-janitor/main.go
- golang/src/image-janitor/main_test.go
- golang/src/jex-adapter/main.go
- golang/src/jex-adapter/main_test.go
- golang/src/job-status-recorder/main.go
- golang/src/job-status-recorder/main_test.go
- golang/src/job-status-to-apps-adapter/main.go
- golang/src/model/jobs_test.go
- golang/src/permissions/restapi/configure_permissions.go
- golang/src/road-runner/main.go
- golang/src/road-runner/main_test.go
- golang/src/templeton/main.go
- golang/src/user-preferences/main.go
- golang/src/user-sessions/main.go
This removes the dependency on the janky C global defined in the configurate package.
> Refactor configurate package to remove C global

- ansible/playbooks/de-condor-launcher.yml
- ansible/playbooks/de-deploy-services.yaml
- ansible/playbooks/de-road-runner.yml
- ansible/roles/util-notify-chat/tasks/main.yaml
Additionally, this makes util-notify-chat not require gathered facts.
> Re-add service deploy notifications

- services/apps/src/apps/service/apps/jobs/submissions.clj
Please review carefully; I'm not sure if this is the right place to be adding this.
Note that this won't work still, for now, because the HTCondor configuration is not correct. But this is a first step.
> CORE-7672: add batch processing group to job JSON in apps

- golang/src/permissions/conversions/grouper-to-perms/main.go
This utility copies all permissions from the Grouper database into the new permissions database.
> grouper-to-perms migration utility

- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/presenter/BelphegorPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorView.java
- ui/de-lib/src/main/java/org/iplantc/de/admin/desktop/client/views/BelphegorViewImpl.java
- ui/de-webapp/src/main/java/org/iplantc/de/conf/AdminWebSecurityConfig.java
This is similar to the change done for DE UI. In addition spring config has to be modified little bit so that when session times out, requests hit the DeCasAuthenticationEntryPoint and gets 401 back.
> CORE-7688 add session time-out redirection logic to belphegor

- docker/images.txt
- docker/manifest-images.txt
- libs/permissions-client/test/permissions_client/integration_test.clj
- services/apps/src/apps/service/apps/agave.clj
- services/apps/src/apps/service/apps/combined.clj
- services/apps/src/apps/service/apps/de.clj
- tools/sharkbait/README.md
This is just a small change, so I'm just going to merge it myself immediately. Anyone who wants to is welcome to review the changes, though.
> Minor documentation, image list, and integration test fixes.

- golang/src/dbutil/connector.go
This is another part of my effort to get the integration tests working consistently. Once again, this is a small change, so I'm planning to merge it immediately. Anyone who wants to review this PR is welcome to do so, however.
> Database ping retries.

- ui/de-webapp/src/main/java/org/iplantc/de/server/websocket/MessageHandler.java
- ui/de-webapp/src/main/java/org/iplantc/de/server/websocket/NotificationHandler.java
- ui/de-webapp/src/main/java/org/iplantc/de/server/websocket/ReceiveNotificationsDirect.java
- ui/de-webapp/src/main/java/org/iplantc/de/server/websocket/amqp/AMQPConnectionManager.java
Turns out that it was logged by our code at ERROR level although it not required. Changed that to INFO level. Refactored other logging messages.
> Core 7702 Frequent 'Unexpectedly disconnected' errors in logs relating to Websockets

- ui/de-lib/src/main/java/org/iplantc/de/client/models/avu/Avu.java
- ui/de-lib/src/main/java/org/iplantc/de/client/util/OntologyUtil.java
- ui/de-lib/src/test/java/org/iplantc/de/client/util/OntologyUtilTest.java
These are the UI changes to complement CORE-7715 (PR #231)
> CORE-7717 Update ontology AVUs to add label AVU to hierarchy AVU

- services/apps/project.clj
- services/apps/src/apps/service/apps/de/edit.clj
- services/apps/src/apps/service/apps/de/metadata.clj
- services/apps/test/apps/service/apps/permissions_test.clj
- services/apps/test/apps/test_fixtures.clj
This change fixes a couple of errors and adds a bunch of integration tests. More integration test conversions (and possibly more bug fixes) are on the way.
> Perms refactor

- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/MetadataView.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/DiskResourceMetadataEditorPanel.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/client/views/metadata/DiskResourceMetadataViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/diskResource/share/DiskResourceModule.java
- ui/de-lib/src/main/java/org/iplantc/de/theme/base/client/diskResource/metadata/MetadataViewDefaultAppearance.java
Since row editing is not supported with checkbox selection model, I have to implement a custom selection model for this.
> Core 7744 Add edit button to metadata view.

- services/apps/src/apps/service/apps/jobs.clj
This fixes a problem with job status updates not working correctly.
> CORE-7759: fixed a problem with job status updates failing

- ui/de-webapp/src/main/java/org/iplantc/de/server/controllers/file/MetadataTemplateDownloadController.java
This PR is just to update end-point to download the csv template and guide in a single zip file.
> core-7729 update end-point

- ui/de-lib/src/main/java/org/iplantc/de/apps/client/AppCategoriesView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/AppsView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/OntologyHierarchiesView.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/AppsViewPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/categories/AppCategoriesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/presenter/hierarchies/OntologyHierarchiesPresenterImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/AppsView.ui.xml
- ui/de-lib/src/main/java/org/iplantc/de/apps/client/views/AppsViewImpl.java
- ui/de-lib/src/main/java/org/iplantc/de/apps/shared/AppsModule.java
- ui/de-lib/src/main/java/org/iplantc/de/commons/client/widgets/DETabPanel.java
This is adding static IDs to the new hierarchy/category tabs within the Apps window.
> CORE-8093 Add static IDs to the tabs within Apps window

- libs/kameleon/src/kameleon/app_listing.clj
This PR fixes schema validation errors in the `GET /apps/categories/:trash-id` app listings endpoint.
The base select query fields from the `kameleon.app-listing/get-app-listing-base-query` were refactored into a new function that could be used by the trash listing query as well, which was previously selecting all columns in the `app_listing` view, causing the listing endpoint to throw schema validation errors for the extra fields.
I also refactored some other query building steps from `get-app-listing-base-query` into new functions, to clean that function up a bit more.
> CORE-8105 Fix Trash app category listing schema validation errors.
